// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef _LIXI_PROJECT_UI_H
#define _LIXI_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen3.h"
#include "ui_Screen4.h"
#include "ui_Screen5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
extern const char * ui_img_13_png;  // assets/13.png
extern const char * ui_img_14_png;  // assets/14.png
extern const char * ui_img_tieude_430x115_png;  // assets/TieuDe_430x115.png
extern const char * ui_img_16_png;  // assets/16.png
extern const char * ui_img_17_png;  // assets/17.png
extern const char * ui_img_19_png;  // assets/19.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
