// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void SavePreChangeSettingScreen(lv_event_t * e);
void ui_RollOffine(lv_event_t * e);
void ui_RollOnline(lv_event_t * e);
void ui_BackToPreScreen(lv_event_t * e);
void ui_ApplySetting(lv_event_t * e);
void ui_HideKeyboard(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
