// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"
#include <Arduino.h>

//Modify Include-----------------

#include <stdlib.h>
#include <esp_random.h>
//Modify Extern
extern void saveConfig_c(const char* ssid, const char* pass, const char* ip, const char* gateway, const char* subnet,
                         bool dhcp, bool m1k, bool m2k, bool m5k, 
                         bool m10k, bool m20k, bool m50k, 
                         bool m100k, bool m200k, bool m500k);
extern void send_spin_now_to_all_clients();
extern uint32_t esp_random(void);
//Modify Varible
lv_obj_t * ui_prev_screen = NULL;

// static const uint16_t money_list[] = {10, 20, 50, 100, 200, 500};
// #define MONEY_COUNT (sizeof(money_list) / sizeof(money_list[0]))
extern uint16_t money_list[9];
extern int active_money_count;


//Modify Function---------------------------
uint16_t get_money_weight(uint16_t value_k) {
  uint32_t full_val = (uint32_t)value_k * 1000;
  if (full_val >= 500000) return 12; // 500k
  if (full_val >= 200000) return 25; // 200k
  if (full_val >= 100000) return 50; // 100k
  return 100; // Các mệnh giá < 100k (10k, 20k, 50k...)
}
////////////////////////////////////

void ui_RollOffline(lv_event_t * e)
{
  
    // uint16_t value = money_list[rand() % active_money_count];
    if (active_money_count == 0) return; // Bảo vệ nếu chưa có tiền trong danh sách

    // --- BƯỚC 1: TÍNH TỔNG TRỌNG SỐ (TOTAL WEIGHT) ---
    uint32_t total_weight = 0;
    for (int i = 0; i < active_money_count; i++) {
      total_weight += get_money_weight(money_list[i]);
    }

    // --- BƯỚC 2: CHỌN NGẪU NHIÊN THEO TRỌNG SỐ ---
    uint32_t r = esp_random() % total_weight; 
    uint16_t selected_value = money_list[0]; // Mặc định

    for (int i = 0; i < active_money_count; i++) {
        uint16_t w = get_money_weight(money_list[i]);
        if (r < w) {
            selected_value = money_list[i];
            break;
        }
        r -= w;
    }

    /* 2. Phân tích hàng số */
    uint8_t hundreds = selected_value / 100;
    uint8_t tens     = (selected_value / 10) % 10;
    uint8_t ones     = selected_value % 10;

    lv_obj_set_style_anim_time(ui_RollerHundreds, 4000, 0);
    lv_obj_set_style_anim_time(ui_RollerTens, 3000, 0);
    lv_obj_set_style_anim_time(ui_RollerOnes, 2000, 0);

    /* 4. Chọn item mục tiêu với animation */
    lv_roller_set_selected(ui_RollerHundreds, hundreds+10, LV_ANIM_ON);
    lv_roller_set_selected(ui_RollerTens, tens+10, LV_ANIM_ON);
    lv_roller_set_selected(ui_RollerOnes, ones+10, LV_ANIM_ON);
}

void ui_RollOnline(lv_event_t * e)
{
	send_spin_now_to_all_clients();
}

void ui_BackToPreScreen(lv_event_t * e)
{
	if (ui_prev_screen == NULL) {
      // Nếu NULL, đổi text của Label1 thành LOI
      // ui_Label1 đã có sẵn trong ui.h nên bạn gọi trực tiếp được
      lv_label_set_text(ui_Label1, "LOI");
  } 
  else if (ui_prev_screen == ui_Screen4) {
      // Nếu là Screen 1
      _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
  } 
  else if (ui_prev_screen == ui_Screen5) {
      // Nếu là Screen 2
      _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
  }
  else if (ui_prev_screen == ui_Screen3) {
      lv_label_set_text(ui_Label1, "SCREEN3");
  }
}

void ui_ApplySetting(lv_event_t * e)
{
	const char * s = lv_textarea_get_text(ui_TextAreWifiName);
  const char * p = lv_textarea_get_text(ui_TextAreWifiPass);
  const char * i = lv_textarea_get_text(ui_TextAreIP);
  const char * g = lv_textarea_get_text(ui_TextAreGateway); 
  const char * sn = lv_textarea_get_text(ui_TextAreSubnet);

  bool dhcp = lv_obj_has_state(ui_CheckboxDHCP, LV_STATE_CHECKED);
  bool m1k  = lv_obj_has_state(ui_Checkbox1000, LV_STATE_CHECKED);
  bool m2k  = lv_obj_has_state(ui_Checkbox2000, LV_STATE_CHECKED);
  bool m5k  = lv_obj_has_state(ui_Checkbox5000, LV_STATE_CHECKED);
  bool m10k = lv_obj_has_state(ui_Checkbox10000, LV_STATE_CHECKED);
  bool m20k = lv_obj_has_state(ui_Checkbox20000, LV_STATE_CHECKED);
  bool m50k = lv_obj_has_state(ui_Checkbox50000, LV_STATE_CHECKED);
  bool m100k = lv_obj_has_state(ui_Checkbox100000, LV_STATE_CHECKED);
  bool m200k = lv_obj_has_state(ui_Checkbox200000, LV_STATE_CHECKED);
  bool m500k = lv_obj_has_state(ui_Checkbox500000, LV_STATE_CHECKED);

  // Gọi hàm đã khai báo extern
  saveConfig_c(s, p, i, g, sn, dhcp, m1k, m2k, m5k, m10k, m20k, m50k, m100k, m200k, m500k);
}

void ui_HideKeyboard(lv_event_t * e)
{
	// Your code here
}



void SavePreChangeSettingScreen(lv_event_t * e)
{
  ui_prev_screen = lv_scr_act();
  _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen3_screen_init);
}


