// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"


// IMAGE DATA: assets/19.png
const char * ui_img_19_png = "S:assets/19.bin";
