// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"


// IMAGE DATA: assets/Picture14_800.png
const char * ui_img_picture14_800_png = "S:assets/ui_img_picture14_800_png.bin";
