// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_SC5LabelVersion;
extern lv_obj_t * ui_SC5LabelIPAdress0;
extern lv_obj_t * ui_SC5LabelWifi;
extern lv_obj_t * ui_Image8;
extern void ui_event_SC5ButtonRoll(lv_event_t * e);
extern lv_obj_t * ui_SC5ButtonRoll;
extern void ui_event_SC5ButtonScreen(lv_event_t * e);
extern lv_obj_t * ui_SC5ButtonScreen;
extern void ui_event_SC5ButtonSetting(lv_event_t * e);
extern lv_obj_t * ui_SC5ButtonSetting;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

