// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_SC2backGround = NULL;
lv_obj_t * ui_SC2LabelVersion = NULL;
lv_obj_t * ui_SC2LabelIPAdress = NULL;
lv_obj_t * ui_SC2LabelWifi = NULL;
lv_obj_t * ui_SC2ButtonSetting = NULL;
lv_obj_t * ui_SC2ButtonScreen1 = NULL;
lv_obj_t * ui_SC2ButtonRoll = NULL;
// event funtions
void ui_event_SC2ButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        SavePreChangeSettingScreen(e);
    }
}

void ui_event_SC2ButtonScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_SC2ButtonRoll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_RollOnline(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SC2backGround = lv_img_create(ui_Screen2);
    lv_obj_set_width(ui_SC2backGround, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC2backGround, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SC2backGround, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SC2backGround, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SC2backGround, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SC2LabelVersion = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SC2LabelVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC2LabelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC2LabelVersion, -383);
    lv_obj_set_y(ui_SC2LabelVersion, 231);
    lv_obj_set_align(ui_SC2LabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC2LabelVersion, "V0.0");
    lv_obj_set_style_text_color(ui_SC2LabelVersion, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC2LabelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC2LabelVersion, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC2LabelIPAdress = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SC2LabelIPAdress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC2LabelIPAdress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC2LabelIPAdress, -297);
    lv_obj_set_y(ui_SC2LabelIPAdress, 231);
    lv_obj_set_align(ui_SC2LabelIPAdress, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC2LabelIPAdress, "192.168.0.100");
    lv_obj_set_style_text_color(ui_SC2LabelIPAdress, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC2LabelIPAdress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC2LabelIPAdress, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC2LabelWifi = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_SC2LabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC2LabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC2LabelWifi, -191);
    lv_obj_set_y(ui_SC2LabelWifi, 231);
    lv_obj_set_align(ui_SC2LabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC2LabelWifi, "Disconnected");
    lv_obj_set_style_text_color(ui_SC2LabelWifi, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC2LabelWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC2LabelWifi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC2ButtonSetting = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_SC2ButtonSetting, 40);
    lv_obj_set_height(ui_SC2ButtonSetting, 40);
    lv_obj_set_x(ui_SC2ButtonSetting, -352);
    lv_obj_set_y(ui_SC2ButtonSetting, -190);
    lv_obj_set_align(ui_SC2ButtonSetting, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC2ButtonSetting, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC2ButtonSetting, lv_color_hex(0xF6BF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC2ButtonSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC2ButtonScreen1 = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_SC2ButtonScreen1, 40);
    lv_obj_set_height(ui_SC2ButtonScreen1, 40);
    lv_obj_set_x(ui_SC2ButtonScreen1, 351);
    lv_obj_set_y(ui_SC2ButtonScreen1, -190);
    lv_obj_set_align(ui_SC2ButtonScreen1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC2ButtonScreen1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC2ButtonScreen1, lv_color_hex(0xF6BF52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC2ButtonScreen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC2ButtonRoll = lv_btn_create(ui_Screen2);
    lv_obj_set_width(ui_SC2ButtonRoll, 250);
    lv_obj_set_height(ui_SC2ButtonRoll, 250);
    lv_obj_set_x(ui_SC2ButtonRoll, -3);
    lv_obj_set_y(ui_SC2ButtonRoll, 86);
    lv_obj_set_align(ui_SC2ButtonRoll, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC2ButtonRoll, 125, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC2ButtonRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC2ButtonRoll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SC2ButtonSetting, ui_event_SC2ButtonSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC2ButtonScreen1, ui_event_SC2ButtonScreen1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC2ButtonRoll, ui_event_SC2ButtonRoll, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_SC2backGround = NULL;
    ui_SC2LabelVersion = NULL;
    ui_SC2LabelIPAdress = NULL;
    ui_SC2LabelWifi = NULL;
    ui_SC2ButtonSetting = NULL;
    ui_SC2ButtonScreen1 = NULL;
    ui_SC2ButtonRoll = NULL;

}
