// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_SC4LabelVersion = NULL;
lv_obj_t * ui_SC4LabelIPAdress0 = NULL;
lv_obj_t * ui_SC4LabelWifi = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_SC4ButtonRoll = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_RollerTens = NULL;
lv_obj_t * ui_RollerHundreds = NULL;
lv_obj_t * ui_RollerOnes = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_SC4ButtonScreen = NULL;
lv_obj_t * ui_SC4ButtonSetting = NULL;
// event funtions
void ui_event_SC4ButtonRoll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_RollOffline(e);
    }
}

void ui_event_SC4ButtonScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen5, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen5_screen_init);
    }
}

void ui_event_SC4ButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        SavePreChangeSettingScreen(e);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x9C0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image1, ui_img_13_png);
    lv_obj_set_width(ui_Image1, 200);
    lv_obj_set_height(ui_Image1, 450);
    lv_obj_set_x(ui_Image1, -300);
    lv_obj_set_y(ui_Image1, -15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image2, ui_img_14_png);
    lv_obj_set_width(ui_Image2, 170);
    lv_obj_set_height(ui_Image2, 450);
    lv_obj_set_x(ui_Image2, 315);
    lv_obj_set_y(ui_Image2, -15);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image3, ui_img_tieude_430x115_png);
    lv_obj_set_width(ui_Image3, 430);
    lv_obj_set_height(ui_Image3, 115);
    lv_obj_set_x(ui_Image3, 15);
    lv_obj_set_y(ui_Image3, -185);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel3, 800);
    lv_obj_set_height(ui_Panel3, 30);
    lv_obj_set_x(ui_Panel3, 0);
    lv_obj_set_y(ui_Panel3, 225);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x9C0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFCE285), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel3, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC4LabelVersion = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_SC4LabelVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC4LabelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC4LabelVersion, -385);
    lv_obj_set_y(ui_SC4LabelVersion, 0);
    lv_obj_set_align(ui_SC4LabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC4LabelVersion, "V0.0");
    lv_obj_set_style_text_color(ui_SC4LabelVersion, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC4LabelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC4LabelVersion, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC4LabelIPAdress0 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_SC4LabelIPAdress0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC4LabelIPAdress0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC4LabelIPAdress0, -300);
    lv_obj_set_y(ui_SC4LabelIPAdress0, 0);
    lv_obj_set_align(ui_SC4LabelIPAdress0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC4LabelIPAdress0, "192.168.0.100");
    lv_obj_set_style_text_color(ui_SC4LabelIPAdress0, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC4LabelIPAdress0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC4LabelIPAdress0, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC4LabelWifi = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_SC4LabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC4LabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC4LabelWifi, -179);
    lv_obj_set_y(ui_SC4LabelWifi, 0);
    lv_obj_set_align(ui_SC4LabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC4LabelWifi, "Disconnected");
    lv_obj_set_style_text_color(ui_SC4LabelWifi, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC4LabelWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC4LabelWifi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Screen4);
    lv_img_set_src(ui_Image4, ui_img_16_png);
    lv_obj_set_width(ui_Image4, 200);
    lv_obj_set_height(ui_Image4, 200);
    lv_obj_set_x(ui_Image4, 0);
    lv_obj_set_y(ui_Image4, 104);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SC4ButtonRoll = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_SC4ButtonRoll, 180);
    lv_obj_set_height(ui_SC4ButtonRoll, 180);
    lv_obj_set_x(ui_SC4ButtonRoll, 0);
    lv_obj_set_y(ui_SC4ButtonRoll, 104);
    lv_obj_set_align(ui_SC4ButtonRoll, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC4ButtonRoll, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC4ButtonRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC4ButtonRoll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC4ButtonRoll, lv_color_hex(0xDFF573), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SC4ButtonRoll, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container1 = lv_obj_create(ui_Screen4);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 430);
    lv_obj_set_height(ui_Container1, 50);
    lv_obj_set_x(ui_Container1, 15);
    lv_obj_set_y(ui_Container1, -63);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RollerTens = lv_roller_create(ui_Container1);
    lv_roller_set_options(ui_RollerTens, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerTens, 50);
    lv_obj_set_height(ui_RollerTens, 50);
    lv_obj_set_x(ui_RollerTens, -95);
    lv_obj_set_y(ui_RollerTens, -1);
    lv_obj_set_align(ui_RollerTens, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerTens, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RollerTens, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_RollerTens, lv_color_hex(0xFEE6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTens, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerTens, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTens, lv_color_hex(0xF71212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTens, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerTens, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerTens, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerTens, lv_color_hex(0xFEE6A6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTens, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTens, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTens, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RollerHundreds = lv_roller_create(ui_Container1);
    lv_roller_set_options(ui_RollerHundreds, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerHundreds, 50);
    lv_obj_set_height(ui_RollerHundreds, 50);
    lv_obj_set_x(ui_RollerHundreds, -145);
    lv_obj_set_y(ui_RollerHundreds, 0);
    lv_obj_set_align(ui_RollerHundreds, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerHundreds, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RollerHundreds, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_RollerHundreds, lv_color_hex(0xFEE6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerHundreds, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerHundreds, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerHundreds, lv_color_hex(0xF71212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerHundreds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerHundreds, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerHundreds, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerHundreds, lv_color_hex(0xFEE6A6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerHundreds, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerHundreds, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerHundreds, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RollerOnes = lv_roller_create(ui_Container1);
    lv_roller_set_options(ui_RollerOnes, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerOnes, 50);
    lv_obj_set_height(ui_RollerOnes, 50);
    lv_obj_set_x(ui_RollerOnes, -45);
    lv_obj_set_y(ui_RollerOnes, 0);
    lv_obj_set_align(ui_RollerOnes, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RollerOnes, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_RollerOnes, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_RollerOnes, lv_color_hex(0xFEE6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerOnes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerOnes, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerOnes, lv_color_hex(0xF71212), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerOnes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RollerOnes, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RollerOnes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerOnes, lv_color_hex(0xFEE6A6), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerOnes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerOnes, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerOnes, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label7, 10);
    lv_obj_set_height(ui_Label7, 50);
    lv_obj_set_x(ui_Label7, -15);
    lv_obj_set_y(ui_Label7, 0);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, ".");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFEE6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label7, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label8, 150);
    lv_obj_set_height(ui_Label8, 50);
    lv_obj_set_x(ui_Label8, 80);
    lv_obj_set_y(ui_Label8, 0);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "000");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFEE6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_Label8, 22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Label8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC4ButtonScreen = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_SC4ButtonScreen, 40);
    lv_obj_set_height(ui_SC4ButtonScreen, 40);
    lv_obj_set_x(ui_SC4ButtonScreen, 329);
    lv_obj_set_y(ui_SC4ButtonScreen, -217);
    lv_obj_set_align(ui_SC4ButtonScreen, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC4ButtonScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC4ButtonScreen, lv_color_hex(0xFBB433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC4ButtonScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC4ButtonSetting = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_SC4ButtonSetting, 40);
    lv_obj_set_height(ui_SC4ButtonSetting, 40);
    lv_obj_set_x(ui_SC4ButtonSetting, -262);
    lv_obj_set_y(ui_SC4ButtonSetting, -217);
    lv_obj_set_align(ui_SC4ButtonSetting, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC4ButtonSetting, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC4ButtonSetting, lv_color_hex(0xFFBE61), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC4ButtonSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SC4ButtonRoll, ui_event_SC4ButtonRoll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC4ButtonScreen, ui_event_SC4ButtonScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC4ButtonSetting, ui_event_SC4ButtonSetting, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Image1 = NULL;
    ui_Image2 = NULL;
    ui_Image3 = NULL;
    ui_Panel3 = NULL;
    ui_SC4LabelVersion = NULL;
    ui_SC4LabelIPAdress0 = NULL;
    ui_SC4LabelWifi = NULL;
    ui_Image4 = NULL;
    ui_SC4ButtonRoll = NULL;
    ui_Container1 = NULL;
    ui_RollerTens = NULL;
    ui_RollerHundreds = NULL;
    ui_RollerOnes = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_SC4ButtonScreen = NULL;
    ui_SC4ButtonSetting = NULL;

}
