// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_SC2backGround;
extern void ui_event_SC2ImgButtonRoll(lv_event_t * e);
extern lv_obj_t * ui_SC2ImgButtonRoll;
extern lv_obj_t * ui_SC2LabelVersion;
extern lv_obj_t * ui_SC2LabelIPAdress;
extern lv_obj_t * ui_SC2LabelWifi;
extern void ui_event_SC2ButtonSetting(lv_event_t * e);
extern lv_obj_t * ui_SC2ButtonSetting;
extern void ui_event_SC2ButtonScreen1(lv_event_t * e);
extern lv_obj_t * ui_SC2ButtonScreen1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

