// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_SC4LabelVersion;
extern lv_obj_t * ui_SC4LabelIPAdress0;
extern lv_obj_t * ui_SC4LabelWifi;
extern lv_obj_t * ui_Image4;
extern void ui_event_SC4ButtonRoll(lv_event_t * e);
extern lv_obj_t * ui_SC4ButtonRoll;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_RollerTens;
extern lv_obj_t * ui_RollerHundreds;
extern lv_obj_t * ui_RollerOnes;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern void ui_event_SC4ButtonScreen(lv_event_t * e);
extern lv_obj_t * ui_SC4ButtonScreen;
extern void ui_event_SC4ButtonSetting(lv_event_t * e);
extern lv_obj_t * ui_SC4ButtonSetting;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

