// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_SC5LabelVersion = NULL;
lv_obj_t * ui_SC5LabelIPAdress0 = NULL;
lv_obj_t * ui_SC5LabelWifi = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_SC5ButtonRoll = NULL;
lv_obj_t * ui_SC5ButtonScreen = NULL;
lv_obj_t * ui_SC5ButtonSetting = NULL;
// event funtions
void ui_event_SC5ButtonRoll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_RollOnline(e);
    }
}

void ui_event_SC5ButtonScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_SC5ButtonSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        SavePreChangeSettingScreen(e);
    }
}

// build funtions

void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen5, lv_color_hex(0x9C0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image5, ui_img_13_png);
    lv_obj_set_width(ui_Image5, 200);
    lv_obj_set_height(ui_Image5, 450);
    lv_obj_set_x(ui_Image5, -300);
    lv_obj_set_y(ui_Image5, -15);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image6 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image6, ui_img_14_png);
    lv_obj_set_width(ui_Image6, 170);
    lv_obj_set_height(ui_Image6, 450);
    lv_obj_set_x(ui_Image6, 315);
    lv_obj_set_y(ui_Image6, -15);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image7, ui_img_17_png);
    lv_obj_set_width(ui_Image7, 430);
    lv_obj_set_height(ui_Image7, 150);
    lv_obj_set_x(ui_Image7, 0);
    lv_obj_set_y(ui_Image7, -165);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_Screen5);
    lv_obj_set_width(ui_Panel1, 800);
    lv_obj_set_height(ui_Panel1, 30);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 225);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x9C0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFCE285), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_TOP, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC5LabelVersion = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_SC5LabelVersion, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC5LabelVersion, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC5LabelVersion, -385);
    lv_obj_set_y(ui_SC5LabelVersion, 0);
    lv_obj_set_align(ui_SC5LabelVersion, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC5LabelVersion, "V0.0");
    lv_obj_set_style_text_color(ui_SC5LabelVersion, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC5LabelVersion, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC5LabelVersion, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC5LabelIPAdress0 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_SC5LabelIPAdress0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC5LabelIPAdress0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC5LabelIPAdress0, -300);
    lv_obj_set_y(ui_SC5LabelIPAdress0, 0);
    lv_obj_set_align(ui_SC5LabelIPAdress0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC5LabelIPAdress0, "192.168.0.100");
    lv_obj_set_style_text_color(ui_SC5LabelIPAdress0, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC5LabelIPAdress0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC5LabelIPAdress0, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC5LabelWifi = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_SC5LabelWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SC5LabelWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SC5LabelWifi, -179);
    lv_obj_set_y(ui_SC5LabelWifi, 0);
    lv_obj_set_align(ui_SC5LabelWifi, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SC5LabelWifi, "Disconnected");
    lv_obj_set_style_text_color(ui_SC5LabelWifi, lv_color_hex(0xF8EA91), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SC5LabelWifi, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SC5LabelWifi, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Screen5);
    lv_img_set_src(ui_Image8, ui_img_19_png);
    lv_obj_set_width(ui_Image8, 250);
    lv_obj_set_height(ui_Image8, 250);
    lv_obj_set_x(ui_Image8, 0);
    lv_obj_set_y(ui_Image8, 75);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SC5ButtonRoll = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_SC5ButtonRoll, 230);
    lv_obj_set_height(ui_SC5ButtonRoll, 230);
    lv_obj_set_x(ui_SC5ButtonRoll, 0);
    lv_obj_set_y(ui_SC5ButtonRoll, 75);
    lv_obj_set_align(ui_SC5ButtonRoll, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC5ButtonRoll, 115, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC5ButtonRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC5ButtonRoll, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC5ButtonRoll, lv_color_hex(0xDFF573), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_SC5ButtonRoll, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SC5ButtonScreen = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_SC5ButtonScreen, 40);
    lv_obj_set_height(ui_SC5ButtonScreen, 40);
    lv_obj_set_x(ui_SC5ButtonScreen, 329);
    lv_obj_set_y(ui_SC5ButtonScreen, -217);
    lv_obj_set_align(ui_SC5ButtonScreen, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC5ButtonScreen, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC5ButtonScreen, lv_color_hex(0xFBB433), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC5ButtonScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SC5ButtonSetting = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_SC5ButtonSetting, 40);
    lv_obj_set_height(ui_SC5ButtonSetting, 40);
    lv_obj_set_x(ui_SC5ButtonSetting, -262);
    lv_obj_set_y(ui_SC5ButtonSetting, -217);
    lv_obj_set_align(ui_SC5ButtonSetting, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_SC5ButtonSetting, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SC5ButtonSetting, lv_color_hex(0xFFBE61), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SC5ButtonSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_SC5ButtonRoll, ui_event_SC5ButtonRoll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC5ButtonScreen, ui_event_SC5ButtonScreen, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SC5ButtonSetting, ui_event_SC5ButtonSetting, LV_EVENT_ALL, NULL);

}

void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_Image5 = NULL;
    ui_Image6 = NULL;
    ui_Image7 = NULL;
    ui_Panel1 = NULL;
    ui_SC5LabelVersion = NULL;
    ui_SC5LabelIPAdress0 = NULL;
    ui_SC5LabelWifi = NULL;
    ui_Image8 = NULL;
    ui_SC5ButtonRoll = NULL;
    ui_SC5ButtonScreen = NULL;
    ui_SC5ButtonSetting = NULL;

}
