// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ButtonSettingBack = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_ButtonSettingOK = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_TextAreWifiName = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_TextAreWifiPass = NULL;
lv_obj_t * ui_TextAreIP = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
// event funtions
void ui_event_ButtonSettingBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_BackToPreScreen(e);
    }
}

void ui_event_ButtonSettingOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        ui_ApplySetting(e);
    }
}

void ui_event_TextAreWifiName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextAreWifiName);
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  0);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  300);
    }
}

void ui_event_TextAreWifiPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextAreWifiPass);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  300);
    }
}

void ui_event_TextAreIP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  0);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_TextAreIP);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_basic_set_property(ui_Keyboard2, _UI_BASIC_PROPERTY_POSITION_Y,  300);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        ui_HideKeyboard(e);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -209);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SETTING");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettingBack = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonSettingBack, 100);
    lv_obj_set_height(ui_ButtonSettingBack, 50);
    lv_obj_set_x(ui_ButtonSettingBack, -340);
    lv_obj_set_y(ui_ButtonSettingBack, -209);
    lv_obj_set_align(ui_ButtonSettingBack, LV_ALIGN_CENTER);
    lv_obj_set_style_text_decor(ui_ButtonSettingBack, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -339);
    lv_obj_set_y(ui_Label3, -209);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Back");

    ui_ButtonSettingOK = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_ButtonSettingOK, 100);
    lv_obj_set_height(ui_ButtonSettingOK, 50);
    lv_obj_set_x(ui_ButtonSettingOK, 339);
    lv_obj_set_y(ui_ButtonSettingOK, -209);
    lv_obj_set_align(ui_ButtonSettingOK, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_ButtonSettingOK, lv_color_hex(0x2DA041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonSettingOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 341);
    lv_obj_set_y(ui_Label5, -209);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "OK");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen3);
    lv_obj_set_width(ui_Panel2, 800);
    lv_obj_set_height(ui_Panel2, 400);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, 33);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_scroll_snap_y(ui_Panel2, LV_SCROLL_SNAP_START);
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreWifiName = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextAreWifiName, 240);
    lv_obj_set_height(ui_TextAreWifiName, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_TextAreWifiName, -90);
    lv_obj_set_y(ui_TextAreWifiName, -170);
    lv_obj_set_align(ui_TextAreWifiName, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreWifiName, "WiFI Name");
    lv_textarea_set_one_line(ui_TextAreWifiName, true);

    ui_Label2 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -331);
    lv_obj_set_y(ui_Label2, -170);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Wifi Name");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -313);
    lv_obj_set_y(ui_Label4, -110);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Wifi Password");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreWifiPass = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextAreWifiPass, 240);
    lv_obj_set_height(ui_TextAreWifiPass, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_TextAreWifiPass, -90);
    lv_obj_set_y(ui_TextAreWifiPass, -110);
    lv_obj_set_align(ui_TextAreWifiPass, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreWifiPass, "WiFI Password");
    lv_textarea_set_one_line(ui_TextAreWifiPass, true);

    ui_TextAreIP = lv_textarea_create(ui_Panel2);
    lv_obj_set_width(ui_TextAreIP, 240);
    lv_obj_set_height(ui_TextAreIP, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_TextAreIP, -90);
    lv_obj_set_y(ui_TextAreIP, -50);
    lv_obj_set_align(ui_TextAreIP, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreIP, "192.168.0.100");
    lv_textarea_set_one_line(ui_TextAreIP, true);

    ui_Label6 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -329);
    lv_obj_set_y(ui_Label6, -50);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "IP Address");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_Screen3);
    lv_obj_set_width(ui_Keyboard2, 800);
    lv_obj_set_height(ui_Keyboard2, 300);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 300);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_BOTTOM_MID);

    lv_obj_add_event_cb(ui_ButtonSettingBack, ui_event_ButtonSettingBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSettingOK, ui_event_ButtonSettingOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreWifiName, ui_event_TextAreWifiName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreWifiPass, ui_event_TextAreWifiPass, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreIP, ui_event_TextAreIP, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label1 = NULL;
    ui_ButtonSettingBack = NULL;
    ui_Label3 = NULL;
    ui_ButtonSettingOK = NULL;
    ui_Label5 = NULL;
    ui_Panel2 = NULL;
    ui_TextAreWifiName = NULL;
    ui_Label2 = NULL;
    ui_Label4 = NULL;
    ui_TextAreWifiPass = NULL;
    ui_TextAreIP = NULL;
    ui_Label6 = NULL;
    ui_Keyboard2 = NULL;

}
