// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_SC1backGround;
extern lv_obj_t * ui_SC1ImageBanner;
extern lv_obj_t * ui_SC1LabelTienLixi;
extern void ui_event_SC1ImgButtonRoll(lv_event_t * e);
extern lv_obj_t * ui_SC1ImgButtonRoll;
extern lv_obj_t * ui_SC1LabelVersion;
extern lv_obj_t * ui_SC1LabelIPAdress;
extern lv_obj_t * ui_SC1LabelWifi;
extern void ui_event_SC1ButtonSetting(lv_event_t * e);
extern lv_obj_t * ui_SC1ButtonSetting;
extern void ui_event_SC1ButtonScreen2(lv_event_t * e);
extern lv_obj_t * ui_SC1ButtonScreen2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

