// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: Lixi_Project

#include "ui.h"

void SavePreChangeSettingScreen(lv_event_t * e)
{
	// Your code here
}

void ui_RollOffine(lv_event_t * e)
{
	// Your code here
}

void ui_RollOnline(lv_event_t * e)
{
	// Your code here
}

void ui_BackToPreScreen(lv_event_t * e)
{
	// Your code here
}

void ui_ApplySetting(lv_event_t * e)
{
	// Your code here
}

void ui_HideKeyboard(lv_event_t * e)
{
	// Your code here
}

void RollOffine(lv_event_t * e)
{
	// Your code here
}

void RollOffline(lv_event_t * e)
{
	// Your code here
}

void ui_RollOffline(lv_event_t * e)
{
	// Your code here
}
